name: Daily Scrape
on:
#  schedule:
#    - cron: 0 10 * * *
  workflow_dispatch:
    inputs:
      skip-update:
        type: boolean
        default: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Launch client-nodes-reporter
        env:
          REPORTER_NOTION_DB: ${{ secrets.REPORTER_NOTION_DB }}
          REPORTER_NOTION_TOKEN: ${{ secrets.REPORTER_NOTION_TOKEN }}
          REPORTER_SLACK_APP_TOKEN: ${{ secrets.REPORTER_SLACK_APP_TOKEN }}
          REPORTER_SLACK_CHANNEL: "core-budget-alerts"
        run: |
          ARGS="--debug --source ethernodes"
          if [ "${{ inputs.skip-update }}" = "true" ]; then
            ARGS="$ARGS --skip-update"
          fi
          go run main.go $ARGS
